package com.tgi.sd.exception;

public class ErrorConstants {

	public static final String STUDENTNAME_IS_REQUIRED = "STUDENTNAME IS REQUIRED";
	public static final String GENDER_IS_REQUIRED ="GENDER IS REQUIRED";
	public static final String DOB_IS_REQUIRED ="DOB IS REQUIRED";
	public static final String PHYSICALLY_CHALLENGED_IS_REQUIRED ="PHYSICALLY CHALLENGED IS REQUIRED";
	public static final String ADMISSIONNUMBER_IS_REQUIRED ="ADMISSIONNUMBER IS REQUIRED";
	public static final String ADMISSIONNUMBER_INVALID_LENGTH ="ADMISSIONNUMBER INVALID LENGTH";
	public static final String ADMISSIONDATE_IS_REQUIRED ="ADMISSIONDATE IS REQUIRED";
	public static final String MEDIUM_IS_REQUIRED ="MEDIUM IS REQUIRED";
	public static final String CLASS_IS_REQUIRED ="CLASS IS REQUIRED";
	public static final String PARENTNAME_IS_REQUIRED ="PARENTNAME IS REQUIRED";
	public static final String PARENTNAME_INVALID_LENGTH ="PARENTNAME INVALID LENGTH";
	public static final String MOBILENUMBER_IS_REQUIRED ="MOBILENUMBER IS REQUIRED";
	public static final String MOBILENUMBER_INVALID_LENGTH ="MOBILENUMBER INVALID LENGTH";
	public static final String DATE_OF_JOINING_IS_REQUIRED ="DATEOFJOINING IS REQUIRED";
	public static final String STAFFNAME_IS_REQUIRED = "STAFFNAME IS REQUIRED"; 
	public static final String STAFFNAME_INVALID_LENGTH ="STAFFNAME INVALID LENGTH";
	public static final String ID_NOT_EXISTS_WHILE_UPDATING ="ID NOT EXISTS WHILE UPDATING";
	public static final String ADMIN_ALREADY_EXISTS = "ADMIN ALREADY EXISTS";
	public static final String USERNAME_ALREADY_EXISTS = "USERNAME ALREADY EXISTS";
	public static final String FIRSTNAME_IS_REQUIRED ="FIRSTNAME IS REQUIRED";
	public static final String FIRSTNAME_INVALID_LENGTH ="FIRSTNAME INVALID LENGTH";
	public static final String COUNTRY_IS_REQUIRED ="COUNTRY IS REQUIRED";
	public static final String STATE_IS_REQUIRED="STATE IS REQUIRED";
	public static final String CITY_IS_REQUIRED ="CITY IS REQUIRED";
	public static final String PINCODE_IS_REQUIRED ="PINCODE IS REQUIRED";
	public static final String COMMUNICATION_ADDRESS_COUNTRY_IS_REQUIRED ="COMMUNICATION ADDRESS  COUNTRY IS REQUIRED";
	public static final String COMMUNICATION_ADDRESS_STATE_IS_REQUIRED ="COMMUNICATION ADDRESS STATE IS REQUIRED";
	public static final String COMMUNICATION_ADDRESS_CITY_IS_REQUIRED ="COMMUNICATION ADDRESS CITY IS REQUIRED";
	public static final String COMMUNICATION_ADDRESS_PINCODE_IS_REQUIRED="COMMUNICATION ADDRESS PINCODE IS REQUIRED";

	public static final String OLD_AND_NEW_PASSWORD_SAME="OLD AND NEW PASSWORD SAME";
	public static final String OLD_PASSWORD_IS_WRONG="OLD PASSWORD IS WRONG";
	public static final String NEW_AND_CONFIRM_PASSWORD_MUST_BE_SAME="NEW AND CONFIRM PASSWORD MUST BE SAME";

	// Generic Messages
	public static final String FAILURE = "FAILURE";
	public static final String SUCCESS = "SUCCESS";
	public static final String REQUEST_MESSAGE = "message";
	public static final String REQUEST_SUCCESS = "Success";
	public static final String REQUEST_FAILURE = "Failure";
	public static final String MANDATORY_CHECK_FAILED = "Missing Field";
	public static final String INVALID_TOKEN = "Invalid Token";
	public static final String AUTH_TYPE = "Invalid Authentication Type";
	public static final String INVALID_USER = "Invalid Username or Password";
	public static final String STATUS_INACTIVE = "User Status Inactive";
	public static final String MISSING_USER = "Username or Password is Missing";
	public static final String INVALID_COMPANY = "INVALID COMPANY OR CLIENT ID";
	public static final String INVALID_JSON_REQUEST = "INVALID JSON REQUEST";
	public static final String INVALID_REQUEST = "INVALID REQUEST";
	public static final String REQUEST_STATUS = "Status";
	public static final String REQUEST_DETAILS = "Details";
	public static final String REQUEST_REASON = "Reason";
	public static final String REPORT_INVALID_DATE_FORMAT ="INVALID DATE FORMAT";
	public static final String JOB_INFORMATION_NOT_FOUND ="Job Information Not Found";
	public static final String LOOKUP_INFORMATION_NOT_FOUND ="Lookup Information Not Found";
	public static final String CLIENT_ORG_INFORMATION_NOT_FOUND = "Client Org Information Not Found";
	public static final String INTER_VIEWER_INFORMATION_NOT_FOUND = "InterViewer Information Not Found";
	public static final String CANDIDATE_INFORMATION_NOT_FOUND = "Candidate Information Not Found";
	public static final String COMPANY_INFORMATION_NOT_FOUND = "Company Information Not Found";
	public static final String IMAGE_INFORMATION_NOT_FOUND = "Image Information Not Found";
	public static final String DEPARTMENT_INFORMATION_NOT_FOUND = "Department Information Not Found";
	public static final String FEEDBACK_INFORMATION_NOT_FOUND = "Feedback Information Not Found";
	public static final String BAD_REQUEST = "Bad Request.";
	public static final String SCHEDULE_INFORMATION_NOT_FOUND = "Schedule Information not found";
	public static final String INTERVIEWER_AVAILABLE_TIME_INFORMATION_NOT_FOUND = "Interviewer Available Time Information not found.";
	public static final String UPLOAD_ERROR_CODE = "UP01"; 
	public static final String SAVE_ERROR_CODE = "SA01"; 
	public static final String REQUEST_ERROR_CODE = "REQ01";
	public static final String INDEX_ERROR_CODE = "IX01"; 
	public static final String ENTITY_IS_EMPTY = "Entity is empty"; 
	public static final String EMAIL_ALREADY_EXIST = "email already exist"; 	
	public static final String NO_ENTITY_OBJECT = "Entity object is null"; 
	public static final String CUSTOMER_NOT_EXISTS = "CustomerId cannot be empty";
	public static final String LIKE_EXISTS = "Like is already exists";
	public static final String DRINK_TICKET_ERROR = "Your next drink will be available in few days";
	public static final String CUSTOMERID_OR_DEVICEID_NOT_EXISTS = "CustomerId or DeviceId cannot be empty";
	public static final String DB_CONNECTION_ERROR = "Connection Error";
	public static final String DUPLICATE_KEY_ERROR = "Duplicate Key error";
	public static final String ENTITY_LIST_EMPTY = "Entity List is empty";
	public static final String FILE_IS_EMPTY = "File is empty";
	public static final String ACTIVITY_NOT_EXISTS = "Invalid Cancel Reservation Request";
	public static final String SMACK_ACCEPT_FRIENDS_ERROR = "Smack error for accept friends";
	public static final String SMACK_CREATION_ERROR = "User not created";
	public static final String PROPERTY_FILE_ERROR = "Property doesn't exists";
	public static final String MOBILENO_NOT_REGISTER_WITH_STUDENT = "Mobile Number not Registered with Student";
	public static final String MOBILENO_ALREADY_REGISTERED = "Mobile Number Already Registered";
	public static final String SCHOOL_INFORMATION_NOT_FOUND = "School Information Not Found";
	public static final String STUDENT_INFORMATION_NOT_FOUND = "Student Information Not Found";
	
}
